version: '3.8'

services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=123456 # 必须设置密码
    command: redis-server --requirepass $${REDIS_PASSWORD}
    restart: unless-stopped

volumes:
  redis_data: