input {
  tcp {
    id => "json_tcp"
    port => 5000
    codec => json_lines
  }

  beats {
    id => "beats"
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dev-logs-%{+YYYY.MM.dd}"
  }
}
